### ISSUE TITLE
Update pub.dev

### ISSUE THREAD

**Issue by joaovvrodrigues** [OctMon/flutter_des#10]

**Comment by OctMon** [comment]
published a new version (2.0.0) of the flutter_des
package to the Dart package site (pub.dev).

For details, go to https://pub.dev/packages/flutter_des/versions/2.0.0

If you have any concerns about this package, file an issue at
https://github.com/dart-lang/pub-dev/issues

Thanks for your contributions to the Dart community!

With appreciation, the Dart package site admin
