### ISSUE TITLE
Unable to determine Swift version on Mac

### ISSUE THREAD

**Issue by Mythar** [OctMon/flutter_des#2]
Please add: s.swift_version = '?.?' to flutter_des.podspec
Where ?.? is the swift version you are using

**Comment by OctMon** [comment]
you can set SWIFT_VERSION in Podfile
for example:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by ethanyou725** [comment]
fatal error: 'flutter_des/flutter_des-Swift.h' file not found,
after set SWIFT_VERSION in Podfile

**Comment by OctMon** [comment]
```
[!] Unable to determine Swift version for the following pods:
    - `flutter_des` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
```

Please check Swift for new projects:

![image](https://user-images.githubusercontent.com/17644890/60232170-5481fa00-98ce-11e9-86f0-92ad3a296e5e.png)

Please try the created project：

![image](https://user-images.githubusercontent.com/17644890/60229440-7d9f8c00-98c8-11e9-9398-79455c5e8add.png)

![image](https://user-images.githubusercontent.com/17644890/60231272-3d8dd880-98cb-11e9-9dc6-242f8453c3fc.png)

![image](https://user-images.githubusercontent.com/17644890/60231278-47174080-98cb-11e9-8b0f-ae6bf2931f32.png)

![image](https://user-images.githubusercontent.com/17644890/60233014-2c47ca80-98d1-11e9-81eb-cdef2da09eb2.png)
