### ISSUE TITLE
how to you set the mode

### ISSUE THREAD

**Issue by premtemp1** [OctMon/flutter_des#4]
Hello,
  How do you set the mode for 3des with this plugin (CBC . ECB)?

Thanks
prem

**Comment by OctMon** [comment]
Thanks for using, wait for time to add this feature, using (CBC. ECB) may result in unsuccessful addition and decryption of passwords.

**Comment by OctMon** [comment]
Sorry, there is not enough time to add new features at the moment, welcome to PR
